import type { BuildId, BuildSpec, GachaFocusBanner, GachaPool, GeoMapConfig } from "./types";

export const BUILD_SPECS: Record<BuildId, BuildSpec> = {
  machine: {
    id: "machine",
    key: "Q",
    name: "机枪塔",
    cost: 80,
    category: "tower",
    role: "ranged",
    description: "射速快，适合处理前期小怪。",
    color: 0x58d68d,
    range: 4.5,
    fireRate: 1.7,
    damage: 18,
    maxHp: 100,
  },
  cannon: {
    id: "cannon",
    key: "W",
    name: "加农炮",
    cost: 150,
    category: "tower",
    role: "mage",
    description: "高伤害范围爆炸，射速较慢。",
    color: 0xffa552,
    range: 4.1,
    fireRate: 0.75,
    damage: 58,
    splash: 1.35,
    maxHp: 120,
  },
  frost: {
    id: "frost",
    key: "E",
    name: "冰霜塔",
    cost: 125,
    category: "tower",
    role: "support",
    description: "低伤害，但会减速敌人。",
    color: 0x72d8ff,
    range: 4.8,
    fireRate: 1.05,
    damage: 9,
    slowFactor: 0.48,
    slowDuration: 1.8,
    maxHp: 100,
  },
  mine: {
    id: "mine",
    key: "R",
    name: "感应地雷",
    cost: 55,
    category: "device",
    role: "device",
    description: "只能放在道路上，一次性范围爆炸。",
    color: 0xf9d857,
    damage: 105,
    triggerRadius: 0.72,
    splash: 1.45,
    maxHp: 1,
  },
  beacon: {
    id: "beacon",
    key: "T",
    name: "能量信标",
    cost: 115,
    category: "device",
    role: "support",
    description: "提升附近防御塔 35% 攻速。",
    color: 0xb68cff,
    buffRange: 3.3,
    buffMultiplier: 1.35,
    maxHp: 80,
  },
  stellar: {
    id: "stellar",
    key: "Y",
    name: "星辉棱镜·天河",
    cost: 320,
    category: "tower",
    role: "mage",
    description: "高阶棱镜法师，范围折射并减速。主动技能：天河审判。",
    color: 0xff4fd8,
    rank: "S",
    requiresUnlock: true,
    city: "jinan",
    range: 6.2,
    maxHp: 420,
    fireRate: 1.25,
    damage: 86,
    splash: 1.25,
    slowFactor: 0.62,
    slowDuration: 1.6,
    activeSkill: {
      name: "天河审判",
      description: "锁定全场敌人造成高额星辉伤害，并大幅减速。",
      cooldown: 18,
    },
  },
  qinqiong: {
    id: "qinqiong",
    key: "1",
    name: "秦琼·门神",
    cost: 260,
    category: "tower",
    role: "melee",
    description: "道路门神，阻挡2名敌人并近战反击。主动技能：不动如山。",
    color: 0xd4af37,
    rank: "S",
    requiresUnlock: true,
    city: "jinan",
    range: 1.2,
    fireRate: 1.15,
    damage: 74,
    maxHp: 780,
    maxBlockCount: 2,
    activeSkill: {
      name: "不动如山",
      description: "恢复生命、短时间大幅减伤并震晕周围敌人。",
      cooldown: 18,
    },
  },
  liqingzhao: {
    id: "liqingzhao",
    key: "2",
    name: "李清照·易安",
    cost: 300,
    category: "tower",
    role: "mage",
    description: "超远水墨群攻，持续压低敌军速度。主动技能：漱玉天潮。",
    color: 0x98ff98,
    rank: "S",
    requiresUnlock: true,
    city: "jinan",
    range: 7.2,
    fireRate: 0.62,
    damage: 140,
    splash: 2.35,
    slowFactor: 0.45,
    slowDuration: 2.4,
    maxHp: 180,
    activeSkill: {
      name: "漱玉天潮",
      description: "大范围水潮爆发，造成高额伤害并冻结行军速度。",
      cooldown: 22,
    },
  },
  bianque: {
    id: "bianque",
    key: "3",
    name: "扁鹊·神医",
    cost: 240,
    category: "tower",
    role: "healer",
    description: "神医支援，持续治疗友军。主动技能：青囊济世。",
    color: 0x4caf50,
    rank: "S",
    requiresUnlock: true,
    city: "jinan",
    fireRate: 0.85,
    healRange: 4.8,
    healAmount: 90,
    maxHp: 260,
    activeSkill: {
      name: "青囊济世",
      description: "全图治疗友军并提供短时减伤，附近敌人受到药毒反噬。",
      cooldown: 24,
    },
  },
};

export const GACHA_POOLS: GachaPool[] = [
  {
    id: "standard",
    name: "标准补给",
    featured: { name: "星辉棱镜·天河", id: "stellar" },
    sPool: ["S 星辉棱镜·天河"],
    featuredImg: "/Arts/Cards/char_stellar.png",
    description: "消耗特派补给卡可抽取全域通用S级防御塔。",
    hardPity: 20,
  },
  {
    id: "jinan-limited",
    name: "济南限定",
    city: "jinan",
    featured: { name: "秦琼·门神", id: "qinqiong" },
    sPool: ["S 秦琼·门神", "S 李清照·易安", "S 扁鹊·神医"],
    featuredImg: "/Arts/Cards/char_qinqiong.png",
    description: "济南限定干员卡池，可选择当期 UP 补给；出 S 时必为所选干员。",
    hardPity: 20,
    focusBanners: [
      {
        id: "qinqiong",
        buildId: "qinqiong",
        name: "秦琼·门神",
        featuredImg: "/Arts/Cards/char_qinqiong.png",
        sRollLabel: "S 秦琼·门神",
      },
      {
        id: "liqingzhao",
        buildId: "liqingzhao",
        name: "李清照·易安",
        featuredImg: "/Arts/Cards/char_liqingzhao.png",
        sRollLabel: "S 李清照·易安",
      },
      {
        id: "bianque",
        buildId: "bianque",
        name: "扁鹊·神医",
        featuredImg: "/Arts/Cards/char_bianque.png",
        sRollLabel: "S 扁鹊·神医",
      },
    ] satisfies GachaFocusBanner[],
  },
];

export const DEFAULT_CESIUM_ION_3D_TILES_ASSET_ID = "2275207";

export const CITY_GEO_CONFIG: Record<string, GeoMapConfig> = {
  beijing: {
    enabled: true,
    provider: "cesium-ion",
    assetId: DEFAULT_CESIUM_ION_3D_TILES_ASSET_ID,
    center: { lat: 39.9163447, lon: 116.3971555, heightMeters: 45 },
    extentMeters: 1400,
    rotationDeg: 0,
    boardHeightMeters: 32,
  },
  shanghai: {
    enabled: true,
    provider: "cesium-ion",
    assetId: DEFAULT_CESIUM_ION_3D_TILES_ASSET_ID,
    center: { lat: 31.2401, lon: 121.4908, heightMeters: 8 },
    extentMeters: 1400,
    rotationDeg: 0,
    boardHeightMeters: 32,
  },
  guangzhou: {
    enabled: true,
    provider: "cesium-ion",
    assetId: DEFAULT_CESIUM_ION_3D_TILES_ASSET_ID,
    center: { lat: 23.1064, lon: 113.3245, heightMeters: 12 },
    extentMeters: 1400,
    rotationDeg: 0,
    boardHeightMeters: 34,
  },
  shenzhen: {
    enabled: true,
    provider: "cesium-ion",
    assetId: DEFAULT_CESIUM_ION_3D_TILES_ASSET_ID,
    center: { lat: 22.5409, lon: 113.9507, heightMeters: 20 },
    extentMeters: 1400,
    rotationDeg: 0,
    boardHeightMeters: 34,
  },
  jinan: {
    enabled: true,
    provider: "cesium-ion",
    assetId: DEFAULT_CESIUM_ION_3D_TILES_ASSET_ID,
    center: { lat: 36.6616, lon: 117.0204, heightMeters: 32 },
    extentMeters: 1200,
    rotationDeg: 0,
    /** 泉港栈桥等泉城关：再上抬 20 m，避免棋盘落在地形下方 */
    boardHeightMeters: 62,
  },
  jinanOlympic: {
    enabled: true,
    provider: "cesium-ion",
    assetId: DEFAULT_CESIUM_ION_3D_TILES_ASSET_ID,
    center: { lat: 36.655, lon: 117.118, heightMeters: 35 },
    extentMeters: 1200,
    rotationDeg: 0,
    boardHeightMeters: 42,
  },
  /** 巴黎区域：城市瓦片落差大，棋盘需在默认抬升上再拔高一档 */
  paris: {
    enabled: true,
    provider: "cesium-ion",
    assetId: DEFAULT_CESIUM_ION_3D_TILES_ASSET_ID,
    center: { lat: 48.8583736, lon: 2.2944813, heightMeters: 40 },
    extentMeters: 2000,
    rotationDeg: 0,
    boardHeightMeters: 80,
    scale: 1,
  },
};

export const CITY_MAP: Record<string, { label: string; defenseIndex: number; exploreIndex: number; geo?: GeoMapConfig }> = {
  beijing: { label: "北京", defenseIndex: 0, exploreIndex: 0, geo: CITY_GEO_CONFIG.beijing },
  shanghai: { label: "上海", defenseIndex: 1, exploreIndex: 1, geo: CITY_GEO_CONFIG.shanghai },
  guangzhou: { label: "广州", defenseIndex: 2, exploreIndex: 2, geo: CITY_GEO_CONFIG.guangzhou },
  shenzhen: { label: "深圳", defenseIndex: 3, exploreIndex: 3, geo: CITY_GEO_CONFIG.shenzhen },
  jinan: { label: "济南", defenseIndex: 4, exploreIndex: 4, geo: CITY_GEO_CONFIG.jinan },
};

export const CITY_EDITOR_ALIASES: Record<string, string[]> = {
  beijing: ["北京", "北京市", "中国·北京", "中国 · 北京"],
  shanghai: ["上海", "上海市", "中国·上海", "中国 · 上海"],
  guangzhou: ["广州", "广州市", "中国·广州", "中国 · 广州"],
  shenzhen: ["深圳", "深圳市", "中国·深圳", "中国 · 深圳"],
  jinan: ["济南", "济南市", "山东·济南", "山东 · 济南", "中国·济南", "中国 · 济南", "泉城", "闯荡山东", "370100", "shandong", "cn-370100", "shandong_370100"],
};