import { CITY_GEO_CONFIG } from "./content";
import { rect } from "./runtime-grid";
import type { MapDefinition } from "./types";

export const MAPS: MapDefinition[] = [
  {
    id: "beijing-hub",
    name: "北京·帝都枢纽",
    description: "皇城根下的防御要塞，古今交汇的战略要地。",
    theme: {
      ground: 0x1a2e1a,
      groundAlt: 0x142414,
      path: 0x2d3e2d,
      obstacle: 0x3e2a1a,
      accent: 0xffeb3b,
      fog: 0x0a140a,
    },
    geo: CITY_GEO_CONFIG.beijing,
    path: [
      { col: 0, row: 13 },
      { col: 5, row: 13 },
      { col: 5, row: 9 },
      { col: 10, row: 9 },
      { col: 10, row: 4 },
      { col: 18, row: 4 },
      { col: 18, row: 11 },
      { col: 27, row: 11 },
    ],
    obstacles: [
      ...rect(2, 2, 4, 2),
      ...rect(12, 7, 3, 2),
      ...rect(21, 3, 3, 3),
      ...rect(2, 15, 5, 2),
      ...rect(22, 14, 4, 2),
    ],
  },
  {
    id: "shanghai-bund",
    name: "上海·外滩沙城",
    description: "黄浦江畔的沙色防线，远程塔和信标的收益更高。",
    theme: {
      ground: 0x81d4fa,
      groundAlt: 0x4fc3f7,
      path: 0xffffff,
      obstacle: 0xffab40,
      accent: 0xffe082,
      fog: 0xe0f7fa,
    },
    geo: CITY_GEO_CONFIG.shanghai,
    path: [
      { col: 0, row: 3 },
      { col: 8, row: 3 },
      { col: 8, row: 14 },
      { col: 15, row: 14 },
      { col: 15, row: 7 },
      { col: 23, row: 7 },
      { col: 23, row: 15 },
      { col: 27, row: 15 },
    ],
    obstacles: [
      ...rect(3, 8, 3, 3),
      ...rect(11, 2, 4, 2),
      ...rect(18, 11, 3, 4),
      ...rect(24, 2, 3, 3),
      ...rect(1, 15, 4, 2),
    ],
  },
  {
    id: "guangzhou-ridge",
    name: "广州·南岭雪径",
    description: "五岭南麓的折线防区，减速塔可以显著延长输出时间。",
    theme: {
      ground: 0xa5d6a7,
      groundAlt: 0x81c784,
      path: 0xfff9c4,
      obstacle: 0xf06292,
      accent: 0xff8a65,
      fog: 0xf1f8e9,
    },
    geo: CITY_GEO_CONFIG.guangzhou,
    path: [
      { col: 0, row: 9 },
      { col: 4, row: 9 },
      { col: 4, row: 3 },
      { col: 12, row: 3 },
      { col: 12, row: 12 },
      { col: 20, row: 12 },
      { col: 20, row: 5 },
      { col: 27, row: 5 },
    ],
    obstacles: [
      ...rect(1, 1, 3, 2),
      ...rect(7, 7, 3, 4),
      ...rect(15, 2, 3, 3),
      ...rect(22, 10, 4, 4),
      ...rect(9, 15, 8, 2),
    ],
  },
  {
    id: "shenzhen-tech",
    name: "深圳·科技裂谷",
    description: "南山科技园的熔岩裂隙，爆炸塔可以覆盖多个路段。",
    theme: {
      ground: 0xe1f5fe,
      groundAlt: 0xb3e5fc,
      path: 0x81d4fa,
      obstacle: 0xba68c8,
      accent: 0xffd54f,
      fog: 0xf5f5f5,
    },
    geo: CITY_GEO_CONFIG.shenzhen,
    path: [
      { col: 0, row: 15 },
      { col: 6, row: 15 },
      { col: 6, row: 11 },
      { col: 14, row: 11 },
      { col: 14, row: 6 },
      { col: 8, row: 6 },
      { col: 8, row: 2 },
      { col: 21, row: 2 },
      { col: 21, row: 9 },
      { col: 27, row: 9 },
    ],
    obstacles: [
      ...rect(2, 3, 4, 4),
      ...rect(10, 14, 5, 3),
      ...rect(17, 5, 3, 5),
      ...rect(23, 12, 4, 4),
      ...rect(11, 8, 2, 2),
    ],
  },
  {
    id: "jinan-harbor",
    name: "济南·泉港栈桥",
    description: "泉城水岸的栈桥防线，经济掉落常出现在开阔水岸区域。",
    theme: {
      ground: 0x80cbc4,
      groundAlt: 0x4db6ac,
      path: 0xe0f2f1,
      obstacle: 0xffd54f,
      accent: 0xffab91,
      fog: 0xe0f2f1,
    },
    geo: CITY_GEO_CONFIG.jinan,
    path: [
      { col: 0, row: 6 },
      { col: 7, row: 6 },
      { col: 7, row: 12 },
      { col: 13, row: 12 },
      { col: 13, row: 8 },
      { col: 19, row: 8 },
      { col: 19, row: 3 },
      { col: 24, row: 3 },
      { col: 24, row: 13 },
      { col: 27, row: 13 },
    ],
    obstacles: [
      ...rect(1, 1, 5, 3),
      ...rect(10, 3, 4, 3),
      ...rect(15, 13, 5, 3),
      ...rect(21, 6, 3, 4),
      ...rect(3, 14, 5, 3),
    ],
  },
];

/** 编辑器热重载前须将 `MAPS` 截断到此长度，再写入 `syncEditorLevelsToRuntime` 的结果 */
export const MAPS_BUILTIN_COUNT = MAPS.length;

export const EXPLORE_MAPS: MapDefinition[] = [
  {
    id: "beijing-neon",
    name: "北京·霓虹街区",
    description: "三里屯到国贸的未来霓虹走廊，探索帝都的每一个角落。",
    theme: {
      ground: 0x05080f,
      groundAlt: 0x0a1220,
      path: 0x1a2b3c,
      obstacle: 0x301015,
      accent: 0x00e5ff,
      fog: 0x020408,
    },
    geo: CITY_GEO_CONFIG.beijing,
    path: [
      { col: 3, row: 9 },
      { col: 10, row: 9 },
      { col: 10, row: 4 },
      { col: 17, row: 4 },
      { col: 17, row: 13 },
      { col: 24, row: 13 },
    ],
    obstacles: [
      ...rect(1, 1, 5, 3),
      ...rect(21, 1, 5, 4),
      ...rect(3, 14, 4, 3),
      ...rect(12, 8, 4, 2),
      ...rect(22, 8, 3, 3),
    ],
  },
  {
    id: "shanghai-loop",
    name: "上海·学院环廊",
    description: "复旦到交大的学院环廊，长廊和小庭院交替出现。",
    theme: {
      ground: 0x065f46,
      groundAlt: 0x064e3b,
      path: 0x047857,
      obstacle: 0x10b981,
      accent: 0xecfdf5,
      fog: 0x022c22,
    },
    geo: CITY_GEO_CONFIG.shanghai,
    path: [
      { col: 4, row: 3 },
      { col: 23, row: 3 },
      { col: 23, row: 14 },
      { col: 4, row: 14 },
      { col: 4, row: 3 },
    ],
    obstacles: [
      ...rect(8, 6, 4, 6),
      ...rect(16, 6, 4, 6),
      ...rect(1, 7, 2, 4),
      ...rect(25, 7, 2, 4),
    ],
  },
  {
    id: "guangzhou-harbor",
    name: "广州·夜港平台",
    description: "南沙港的夜间集装箱区，掉落点更分散。",
    theme: {
      ground: 0x1e3a8a,
      groundAlt: 0x1e40af,
      path: 0x1d4ed8,
      obstacle: 0x60a5fa,
      accent: 0xdbeafe,
      fog: 0x172554,
    },
    geo: CITY_GEO_CONFIG.guangzhou,
    path: [
      { col: 2, row: 5 },
      { col: 9, row: 5 },
      { col: 9, row: 11 },
      { col: 18, row: 11 },
      { col: 18, row: 6 },
      { col: 26, row: 6 },
    ],
    obstacles: [
      ...rect(1, 13, 7, 3),
      ...rect(12, 2, 5, 3),
      ...rect(20, 10, 5, 5),
      ...rect(3, 8, 3, 2),
    ],
  },
  {
    id: "shenzhen-park",
    name: "深圳·欢乐海岸",
    description: "华侨城欢乐海岸的活动风格地图，色块鲜明。",
    theme: {
      ground: 0x4c1d95,
      groundAlt: 0x5b21b6,
      path: 0x6d28d9,
      obstacle: 0x8b5cf6,
      accent: 0xede9fe,
      fog: 0x2e1065,
    },
    geo: CITY_GEO_CONFIG.shenzhen,
    path: [
      { col: 5, row: 15 },
      { col: 5, row: 9 },
      { col: 12, row: 9 },
      { col: 12, row: 3 },
      { col: 21, row: 3 },
      { col: 21, row: 12 },
      { col: 26, row: 12 },
    ],
    obstacles: [
      ...rect(1, 2, 5, 5),
      ...rect(8, 13, 5, 3),
      ...rect(15, 7, 4, 4),
      ...rect(22, 15, 4, 2),
    ],
  },
  {
    id: "jinan-terrace",
    name: "济南·趵突露台",
    description: "趵突泉畔的高空露台，留出大片移动空间。",
    theme: {
      ground: 0x90a0b8,
      groundAlt: 0x8598ae,
      path: 0xe2ecff,
      obstacle: 0x6078a0,
      accent: 0xbefffc,
      fog: 0xa0b0c8,
    },
    geo: CITY_GEO_CONFIG.jinanOlympic,
    path: [
      { col: 2, row: 8 },
      { col: 8, row: 8 },
      { col: 8, row: 3 },
      { col: 19, row: 3 },
      { col: 19, row: 14 },
      { col: 26, row: 14 },
    ],
    obstacles: [
      ...rect(1, 1, 4, 3),
      ...rect(10, 10, 4, 4),
      ...rect(15, 6, 3, 3),
      ...rect(23, 2, 4, 4),
      ...rect(4, 14, 5, 2),
    ],
  },
];

export const EXPLORE_MAPS_BUILTIN_COUNT = EXPLORE_MAPS.length;
